manageauthorizedips: 1
authorizedips:
        - "127.0.0.1"
debug: 0
allow_renewal: 0
allow_nonfree_renewal: 0
# fields from the borrowers table to be sent by the today and all services
#borrowerfields:
#        - "surname"
#        - "firstname"
#        - "zipcode"
